### PR TITLE
bumping catalogBranch to 1.3.x

### PR DESCRIPTION
**Pull request by elai-shalev**

### CODE REVIEW

**Comment by elai-shalev** [comment]
@masayag

**Review by masayag — APPROVED** [review]

**Review by gabriel-farache — APPROVED** [review]

**Comment by jenniferubah** [comment]
@ElaiShalevRH please could you rebase the PR

**Review by jenniferubah — APPROVED** [review]

**Review by jordigilh — APPROVED** [review]

**Comment by jordigilh** [comment]
~~I think you're missing updating the `values.yaml` file, right?~~ Nope, it's been updated already. All good :)

**Comment by elai-shalev** [comment]
Thanks all, 
If anyone could just merge that would be great :)

**Pull request merged**
